#URL do ViaCep:
quarkus.rest-client.viacep-api.url=https://viacep.com.br/ws

#URL da Api do Google Maps
quarkus.rest-client.google-maps-api.url=https://routes.googleapis.com

#Chave da Api do Google Maps
google-api-key=AIzaSyCBIs0yFvfm-y5qVU31hjN24-KI9u5mw_U

#Estilização do Swagger
quarkus.swagger-ui.theme=original

quarkus.smallrye-openapi.info-title=Checkpoint 5
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Checkpoint 5 da materia Domain Driven Design using Java, envolvendo o uso de APIs

quarkus.datasource.db-kind=oracle
quarkus.datasource.username=RM566667
quarkus.datasource.password=fiap26
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl

quarkus.rest-client.disable-default-mapper=true