# URL do ViaCep
quarkus.rest-client.viacep-api.url=https://viacep.com.br/ws

# URL da Api do Google Maps
quarkus.rest-client.google-maps-api.url=https://routes.googleapis.com

# Chave da Api do Google Maps (Placeholder)
# Obtenha sua chave em: https://console.cloud.google.com/google/maps-apis/credentials
google-api-key=SUA_CHAVE_GOOGLE_AQUI

# Estilização do Swagger
quarkus.swagger-ui.theme=original

# Informações da API (OpenAPI)
quarkus.smallrye-openapi.info-title=Checkpoint 5
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Checkpoint 5 da materia Domain Driven Design using Java, envolvendo o uso de APIs

# Configurações do Banco de Dados Oracle (Placeholder)
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=SEU_USUARIO_RM
quarkus.datasource.password=SUA_SENHA_FIAP
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl

# Desabilitar mapper padrão para o Rest Client
quarkus.rest-client.disable-default-mapper=true